# Generated by Django 2.0.6 on 2018-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0002_auto_20180831_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='id',
        ),
        migrations.AlterField(
            model_name='branches',
            name='Branch',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
