# Generated by Django 2.0.6 on 2018-08-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0004_auto_20180831_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
