# Generated by Django 2.0.6 on 2018-08-31 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0005_auto_20180831_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
