# Generated by Django 2.0.6 on 2018-08-31 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Newapp', '0009_auto_20180831_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branches',
            name='Branch',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='register',
            name='Branch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Newapp.Branches'),
            preserve_default=False,
        ),
    ]
